### ISSUE TITLE
Question about the optimization of attack

### ISSUE THREAD

**Issue by cuge1995** [ajhamdi/AdvPC#3]
why in the paper the AdvPC is optimized by PGD, but in the code is C&W attack?

**Comment by ajhamdi** [comment]
both options are available in the code. you can use the flag `hard_bound_mode` to determine the type of bound as follows 
`hard_bound_mode` = 0 : no bound -> C&W attack with `beta_two` and `beta_infty` control over the regularizer
`hard_bound_mode` = 1 : PGD with  $\el_\infty$ on the attack  with `u_infty` as  $\el_\infty$ upper bound 
`hard_bound_mode` = 2 : PGD with  $\el_2$ on the attack  with `u_two` as  $\el_2$ upper bound 
  
**most results in the paper are reported using options 1 and 2**
