### ISSUE TITLE
Training dataset partitioning

### ISSUE THREAD

**Issue by BiheZhao** [ajhamdi/AdvPC#8]
Thanks for your amazing work!
Could you please give the details on dataset partitioning for training each network? Your ECCV paper mentions that AE is trained on the full Modelnet40, but it seems the training dataset partitioning for the victim model (the attacked model) and source model (the surrogate model possessed by the attacker) are not provided. Are they both trained on the full Modelnet40 or different parts of Modelnet40?
Much appreciated if you could provide this information.

**Comment by ajhamdi** [comment]
all the networks are trained on the full ModelNet 40 training partition
